FROM alpine:3.12 as BUILDER

RUN [ "apk", "add", "--no-cache", \
    "binutils=2.34-r1", \
    "clang=10.0.0-r2", \
    "cmake=3.17.2-r0", \
    "g++=9.3.0-r2", \
    "gcc=9.3.0-r2", \
    "git=2.26.2-r0", \
    "make=4.3-r0", \
    "musl-dev=1.1.24-r9" \
]

ARG CC=clang
ARG CXX=clang++

RUN [ "git", "clone", "--recursive", "https://github.com/cuberite/cuberite.git", "/tmp/src" ]

WORKDIR /tmp/src/Release

RUN [ "cmake", "-DCMAKE_BUILD_TYPE=RELEASE", ".." ]
RUN [ "make", "--jobs={$NPROC}" ]
